config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    resources :order_details, only: [:update]
    # patch 'order_details/:id', to: 'order_details#update'

    resources :orders, only: [:show, :update]
    # get 'orders/:id', to: 'orders#show'
    # patch 'orders/:id', to: 'orders#update'

    resources :customers, only: [:index, :show, :edit, :update]
    # get 'customers', to: 'customers#index'
    # get 'customers/:id', to: 'customers#show'
    # get 'customers/:id/edit', to: 'customers#edit'
    # patch 'customers/:id', to: 'customers#update'

    resources :genres, only: [:index, :create, :edit, :update]
    # get 'genres', to: 'genres#index'
    # post 'genres', to: 'genres#create'
    # get 'genres/:id/edit', to: 'genres#edit'
    # patch 'genres/:id', to: 'genres#update'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    # get 'items', to: 'items#index'
    # get 'items/new'
    # post 'items', to: 'items#create',as: "items"
    # get 'items/:id', to: 'items#show'
    # get 'items/:id/edit', to: 'items#edit'
    # patch 'items/:id', to: 'items#update'

    root to: 'homes#top'
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    # get 'addresses', to: 'address#index'
    # get 'addresses/:id/edit', to: 'address#edit'
    # post 'addresses', to: 'address#create'
    # get 'addresses/:id', to: 'address#update'
    # get 'addresses/:id', to: 'address#destroy'


    # get 'orders/new'
    post 'orders/confirm'
    get 'orders/complete'
    # post 'orders', to: 'cart_items#create'
    # get 'orders', to: 'cart_items#index'
    # get 'orders/:id', to: 'cart_items#show'
    resources :orders, only: [:new, :create, :index, :show]

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    # get 'cart_items', to: 'cart_items#index'
    # patch 'cart_items/:id', to: 'cart_items#update'
    # delete 'cart_items/:id', to: 'cart_items#destroy'

    # post 'cart_items', to: 'cart_items#create'

    get 'customers/my_page', to: 'customers#show'
    get 'customers/information/edit', to: 'customers#edit'
    patch 'customers/information', to: 'customers#update'
    get 'customers/unsubscribe', to: 'customers#unsubscribe'
    patch 'customers/withdraw', to: 'customers#withdraw'

    resources :items, only: [:index, :show]
    # get 'items', to: 'items#index'
    # get 'items/:id', to: 'items#show'

    root to: 'homes#top'
    get 'about', to: 'homes#about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # enum is_deleted: { false: 0, true: 1 }

  # def active_for_authentication?
  #   super && (is_deleted == false)
  # end

  def customer_status
    if is_deleted
      "退会"
    else
      "有効"
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(is_deleted: true)
      flash[:notice] = 'Successfully updated customer'
      redirect_to admin_customer_path(@customer.id)
    else
      @customer = Customer.find(params[:id])
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:customer_status)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>

<h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>

<p>会員ID</p>
<%= @customer.id %>

<p>氏名</p>
<label for="inputLastName"></label>
<%= f.text_field :last_name, autofocus: true, id:"inputLastName",　placeholder: "令和" %>
<label for="inputFirstName"></label>
<%= f.text_field :first_name, autofocus: true, id:"inputFirstName", placeholder:"道子" %>

<p>フリガナ</p>
<label for="inputLastNameKana"></label>
<%= f.text_field :last_name_kana, autofocus: true, id:"inputLastNameKana",　placeholder: "レイワ" %>
<label for="inputFirstName"></label>
<%= f.text_field :first_name_kana, autofocus: true, id:"inputFirstNameKana", placeholder: "ミチコ" %>

<p>郵便番号</p>
<label for="inputPostalCode"></label>
<%= f.text_field :postal_code, autofocus: true, id:"inputPostalCode", placeholder: "0000000" %>

<p>住所</p>
<label for="inputAddress"></label>
<%= f.text_field :address, autofocus: true, id:"inputAddress", placeholder: "東京都渋谷区代々木神園町0-0" %>

<p>電話番号</p>
<label for="inputTelephoneNumber"></label>
<%= f.text_field :telephone_number, autofocus: true, id:"inputTelephoneNumber", placeholder: "0000000" %>

<p>メールアドレス</p>
<label for="inputEmail"></label>
<%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder: "sample@example.com" %>

<p>会員ステータス</p>
<label for="inputIsDeleted"></label>
<%= f.radio_button :is_deleted, :false, autofocus: true, id:"inputIsDleted" %>
有効
<%= f.radio_button :is_deleted, :ture, autofocus: true, id:"inputIsDleted" %>
退会

<div class="text-center">
  <button type="submit" class="btn btn-success">変更を保存</button>
</div>

<% end %>

app/views/admin/customers/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-2 "></div>
    <div class="col-md-8">
      <h2>会員一覧</h2>

      <ul class="customers">
        <table class = "table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <% @customers.each do |customer| %>
          <tbody>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer) do %>
                  <%= customer.last_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <td><%= customer.customer_status %></td>
              <td></td>
            </tr>
          </tbody>
          <% end %>

        </table>
        <%= paginate @customers %>
      </ul>
    </div>
  </div>
  <div class="col-md-2 "></div>
</div>

app/views/admin/customers/show.html.erb
<div class="container px-5 px-sm-0">

  <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>

  <table class="table table-borderless">
    <thead>
      <tr></tr>
    </thead>
    <tbody>
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.last_name %><%= @customer.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td><%= @customer.customer_status %></td>
      </tr>
    </tbody>
  </table>

  <div class="text-center">
    <%= link_to edit_admin_customer_path(@customer) do %>
      <button type="submit" class="btn btn-success">編集する</button>
    <% end %>

    <%= link_to admin_order_path(@customer) do %>
      <button type="submit" class="btn btn-primary">注文履歴一覧を見る</button>
    <% end %>
  </div>

</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>