config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    resources :order_details, only: [:update]
    # patch 'order_details/:id', to: 'order_details#update'

    resources :orders, only: [:show, :update]
    # get 'orders/:id', to: 'orders#show'
    # patch 'orders/:id', to: 'orders#update'

    resources :customers, only: [:index, :show, :edit, :update]
    # get 'customers', to: 'customers#index'
    # get 'customers/:id', to: 'customers#show'
    # get 'customers/:id/edit', to: 'customers#edit'
    # patch 'customers/:id', to: 'customers#update'

    resources :genres, only: [:index, :create, :edit, :update]
    # get 'genres', to: 'genres#index'
    # post 'genres', to: 'genres#create'
    # get 'genres/:id/edit', to: 'genres#edit'
    # patch 'genres/:id', to: 'genres#update'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    # get 'items', to: 'items#index'
    # get 'items/new'
    # post 'items', to: 'items#create',as: "items"
    # get 'items/:id', to: 'items#show'
    # get 'items/:id/edit', to: 'items#edit'
    # patch 'items/:id', to: 'items#update'

    root to: 'homes#top'
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    # get 'addresses', to: 'address#index'
    # get 'addresses/:id/edit', to: 'address#edit'
    # post 'addresses', to: 'address#create'
    # get 'addresses/:id', to: 'address#update'
    # get 'addresses/:id', to: 'address#destroy'


    # get 'orders/new'
    post 'orders/confirm'
    get 'orders/complete'
    # post 'orders', to: 'cart_items#create'
    # get 'orders', to: 'cart_items#index'
    # get 'orders/:id', to: 'cart_items#show'
    resources :orders, only: [:new, :create, :index, :show]

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    # get 'cart_items', to: 'cart_items#index'
    # patch 'cart_items/:id', to: 'cart_items#update'
    # delete 'cart_items/:id', to: 'cart_items#destroy'

    # post 'cart_items', to: 'cart_items#create'

    get 'customers/my_page', to: 'customers#show'
    get 'customers/information/edit', to: 'customers#edit'
    patch 'customers/information', to: 'customers#update'
    get 'customers/unsubscribe', to: 'customers#unsubscribe'
    patch 'customers/withdraw', to: 'customers#withdraw'

    resources :items, only: [:index, :show]
    # get 'items', to: 'items#index'
    # get 'items/:id', to: 'items#show'

    root to: 'homes#top'
    get 'about', to: 'homes#about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: {wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4}

  # def subtotal
    # @order_details.tax_price * @order_details.amount
  # end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    # @customer = Customer.find(params[:id])
    # @orders = @customer.orders.page(params[:page])

    # @order_details = OrderDetail.where(order_id: params[:id])
    # @order = Order.find(params[:id])

    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @shipping_fee = 800
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details

    if @order.order_status == "confirm_payment"
      @order_details.update_all(making_status: "waiting_manufacture")

      # @order_details.each do |order_detail|
        # order_detail.making_status = 1
        # order_detail.update(making_status: "waiting_manufacture")
        # order_detail.update
      # end
    end
    redirect_to admin_order_path
  end

  private

    def order_params
      params.require(:order).permit(:order_status)
    end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="col-md-1">
    </div>

    <div class="col-md-10 offset-md-1">

<h2>注文履歴詳細</h2>

<%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
  <table>
    <tr>
      <td>購入者</td>
      <td>
        <%= link_to admin_customer_path(@order.customer) do %>
          <%= @order.customer.first_name %><%= @order.customer.last_name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>注文日</td>
      <td><%= l @order.created_at %></td>
    </tr>
    <tr>
      <td>配送先</td>
      <td>
        〒<%= @order.shipping_postal_code%><%= @order.shipping_address %><br>
        <%= @order.shipping_name %>
      </td>
    </tr>
    <tr>
      <td>支払い方法</td>
      <td><%= @order.payment_method_i18n%></td>
    </tr>
    <tr>
      <td>注文ステータス</td>
      <td>
        <%= f.select :order_status, Order.order_statuses_i18n.invert %>
        <%= f.submit "更新", class: "btn btn-success" %>
      </td>
    </tr>
  </table>
<% end %>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
    </tr>
  </thead>

  <% @total = 0 %>


  <tbody>
    <% @order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item.name %></td>
      <td><%= (order_detail.item.with_tax_price).floor.to_s(:delimited) %></td>
      <td><%= order_detail.amount %></td>
      <td>
        ￥<%= (order_detail.tax_price * order_detail.amount).to_s(:delimited) %>
        <% @total += (order_detail.tax_price * order_detail.amount) %>
      </td>
      <td>
        <%= form_with model: order_detail , url: admin_order_detail_path(order_detail) , method: :patch , local: true do |f| %>
        <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
        <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

 <div class="col-md-4 offset-md-7">
  <table>
    <tr>
      <td>商品合計</td>
      <td><%= @total %>円</td>
    </tr>
    <tr>
      <td>送料</td>
      <td><%= @shipping_fee %>円</td>
    </tr>
    <tr>
      <td>請求金額合計</td>
      <td><%= @total + @shipping_fee %>円</td>
    </tr>
  </table>

</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>