config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    resources :order_details, only: [:update]
    # patch 'order_details/:id', to: 'order_details#update'

    resources :orders, only: [:show, :update]
    # get 'orders/:id', to: 'orders#show'
    # patch 'orders/:id', to: 'orders#update'

    resources :customers, only: [:index, :show, :edit, :update]
    # get 'customers', to: 'customers#index'
    # get 'customers/:id', to: 'customers#show'
    # get 'customers/:id/edit', to: 'customers#edit'
    # patch 'customers/:id', to: 'customers#update'

    resources :genres, only: [:index, :create, :edit, :update]
    # get 'genres', to: 'genres#index'
    # post 'genres', to: 'genres#create'
    # get 'genres/:id/edit', to: 'genres#edit'
    # patch 'genres/:id', to: 'genres#update'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    # get 'items', to: 'items#index'
    # get 'items/new'
    # post 'items', to: 'items#create',as: "items"
    # get 'items/:id', to: 'items#show'
    # get 'items/:id/edit', to: 'items#edit'
    # patch 'items/:id', to: 'items#update'

    root to: 'homes#top'
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    # get 'addresses', to: 'address#index'
    # get 'addresses/:id/edit', to: 'address#edit'
    # post 'addresses', to: 'address#create'
    # get 'addresses/:id', to: 'address#update'
    # get 'addresses/:id', to: 'address#destroy'


    # get 'orders/new'
    post 'orders/confirm'
    get 'orders/complete'
    # post 'orders', to: 'cart_items#create'
    # get 'orders', to: 'cart_items#index'
    # get 'orders/:id', to: 'cart_items#show'
    resources :orders, only: [:new, :create, :index, :show]

    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    # get 'cart_items', to: 'cart_items#index'
    # patch 'cart_items/:id', to: 'cart_items#update'
    # delete 'cart_items/:id', to: 'cart_items#destroy'

    # post 'cart_items', to: 'cart_items#create'

    get 'customers/my_page', to: 'customers#show'
    get 'customers/information/edit', to: 'customers#edit'
    patch 'customers/information', to: 'customers#update'
    get 'customers/unsubscribe', to: 'customers#unsubscribe'
    patch 'customers/withdraw', to: 'customers#withdraw'

    resources :items, only: [:index, :show]
    # get 'items', to: 'items#index'
    # get 'items/:id', to: 'items#show'

    root to: 'homes#top'
    get 'about', to: 'homes#about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class="navbar navbar-dark bg-dark">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">NaganoCake</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
        <%# if request.fullpath.include? "/admin" %>
          <li class="nav-item">
            <%= link_to admin_items_path, class: 'nav-link text-white' do %>
              商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_customers_path, class: 'nav-link text-white' do %>
              会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_root_path, class: 'nav-link text-white' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_genres_path, class: 'nav-link text-white' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-white' do %>
              ログアウト
            <% end %>
          </li>
          <% elsif customer_signed_in? %>
      <!--userログインの状態時表示したいheaderのメニュ-->
          <div class="text-white">
            ようこそ、<%= current_customer.last_name %>さん！
          </div>

          <li class="nav-item">
            <%= link_to customers_my_page_path(current_customer.id), class: 'nav-link text-white' do %>
              マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: 'nav-link text-white' do %>
              商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to cart_items_path, class: 'nav-link text-white' do %>
              カート
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-white' do %>
              ログアウト
            <% end %>
          </li>

      <% else %>
      <!--ログインしてないときに表示する-->
        <li class="nav-item">
          <%= link_to about_path, class: 'nav-link text-white' do %>
            About
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to items_path, class: 'nav-link text-white' do %>
            商品一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_customer_registration_path, class: 'nav-link text-white' do %>
            新規登録
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_customer_session_path, class: 'nav-link text-white' do %>
            ログイン
          <% end %>
        </li>
      <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
      <div><%= flash[:notice] %></div>
    <%= yield %>
    </main>

    <footer class="navbar navbar-dark bg-dark">>
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p></p>
          </div>
        </div>
      </div>
    </footer>

  </body>


</html>